
routingAccueil:
    resource:  "@EcomBundle/Resources/config/routing/routingAccueil.yml"
    prefix: /

routingProduits:
    resource:  "@EcomBundle/Resources/config/routing/routingProduits.yml"
    prefix: /

routingPanier:
    resource:  "@EcomBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingCommande:
    resource:  "@EcomBundle/Resources/config/routing/routingCommande.yml"
    prefix: /
