#routingAvisAdmin:
#    resource: "@EcomBundle/Resources/config/routing/routingAvisAdmin.yml"
#    prefix:   /admin/avis

#routingTarifAdmin:
#    resource: "@EcomBundle/Resources/config/routing/routingTarifAdmin.yml"
#    prefix:   /admin/Tarif

#routingAdmin:
#    resource:  "@EcomBundle/Resources/config/routing/routingAdmin.yml"
#    prefix: /admin

#routingCommandesAdmin:
#    resource: "@EcomBundle/Resources/config/routing/routingCommandesAdmin.yml"
#    prefix:   /admin/commandes

#routingCategoriesAdmin:
#    resource: "@EcomBundle/Resources/config/routing/routingCategoriesAdmin.yml"
#    prefix:   /admin/categories

#routingProduitsAdmin:
#    resource: "@EcomBundle/Resources/config/routing/routingProduitsAdmin.yml"
#    prefix:   /admin/produits

routingProduits:
    resource:  "@EcomBundle/Resources/config/routing/routingProduits.yml"
    prefix: /

routingPanier:
    resource:  "@EcomBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingCommande:
    resource:  "@EcomBundle/Resources/config/routing/routingCommande.yml"
    prefix: /
