parameters:
#    ecom.example.class: DV\EcomBundle\Example

services:
    tva:
        class: DV\EcomBundle\Twig\Extension\TvaExtension
        tags:
          - { name: twig.extension}

    montantTva:
        class: DV\EcomBundle\Twig\Extension\MontantTvaExtension
        tags:
          - { name: twig.extension}

    redirectionListener:
        class: DV\EcomBundle\Listener\RedirectionListener
        arguments: [@service_container, @session]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }     

    setNewReference:
        class:  DV\EcomBundle\Services\GetReference
        arguments: [@security.context, @doctrine.orm.entity_manager]

    setNewFacture:
        class:  DV\EcomBundle\Services\GetFacture
        arguments: [@service_container]

    setNewBL:
        class:  DV\EcomBundle\Services\GetBL
        arguments: [@service_container]