pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

ecom:
    resource: "@EcomBundle/Resources/config/routing.yml"
    prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /


