<?php

namespace DV\EcomBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArticles()
	{
		$qb = $this->createQueryBuilder('a')
			->where('a.datedeb <= :now')
			->andWhere('a.datefin IS NULL')
			->orWhere('a.datedeb <= :now')
			->andWhere('a.datefin >= :now')
			->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
			;
		return $qb->getQuery()->getResult();
	}
}
