<?php

namespace DV\EcomBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
	public function findByFacture($utilisateur)
	{
		$qb = $this->createQueryBuilder('c')
			->select('c')
			->where('c.utilisateur = :utilisateur')
			->andWhere('c.valider = 1')
			->andWhere('c.reference != 0')
			->orderBy('c.id')
			->setParameter('utilisateur', $utilisateur);
		return $qb->getQuery()->getResult();		
	}

	public function findNomPrenom($utilisateur)
	{
		//On envoie un tableau contenant nos produits...
		$qb = $this->createQueryBuilder('c')
			->join('c.utilisateur','u')
			->where('u.id = :utilisateur')
			->orderBy('c.date', 'desc') 
			->setMaxResults(1)
			->setParameter('utilisateur', $utilisateur);
		return $qb->getQuery()->getResult();		
	}

	public function findAvecPreparer($v)
	{
		if($v=='0')
		{	$qb = $this->createQueryBuilder('c')
			->select('c')
			->where('c.preparer <= :v')
			->orderBy('c.id')
			->setParameter('v', $v);
		}
		else
		{	$qb = $this->createQueryBuilder('c')
			->select('c')
			->where('c.preparer >= :v')
			->orderBy('c.id')
			->setParameter('v', $v);
		}
		return $qb->getQuery()->getResult();		
	}

	public function findLastRef()
	{
		$qb = $this->createQueryBuilder('c')
			->select('c.reference')
			->where('c.reference LIKE :regex' )
			->andWhere('c.valider = 1')
			->orderBy('c.reference', 'desc') 			
			->setMaxResults(1)
			->setParameter('regex', '1%');
		return $qb->getQuery()->getResult();
	}
}
