<?php

namespace DV\EcomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
	public function findArray($array)
	{
		//On envoie un tableau contenant nos produits...

		$qb = $this->createQueryBuilder('pd')
			->select('pd')
			->where('pd.id IN (:array)')	
			//->join('pd.promoProd','pm')
			//->andWhere('pm.datedeb = MAX(pm.datedeb)')
			//->groupBy('pm.produit')
			//->having('pm.datedeb <= :now')
			//->andHaving('pm.datefin >= :now')
			//->andHaving('')
			//->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)					
			->setParameter('array', $array);

		/* Départ ProduitsRepository */
		/*$subqb = $this->createQueryBuilder('prd1')	
			->select('p','max(p.datedeb)')
			->from('DV\EcomBundle\Entity\PromoProds','p')
			->where( ':now BETWEEN p.datedeb AND p.datefin')
			->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
			->groupBy('p.produit');

		$qb = $this->createQueryBuilder('prd')
			->leftjoin('prd.promoProd','prm')
			->addSelect('prm');

		$qb = $qb
			->andWhere($qb->expr()->in('prd.promoProd', $subqb->getDQL()));
		
		$qb = $qb
			->andWhere('prd.disponible = 1')
			->andWhere('prd.id IN (:array)')	
			->setParameter('array', $array)
			->orderBy('prd.id');*/
		/*$subqb = $this->createQueryBuilder('p1')
			->select('p2')
			->from('EcomBundle:PromoProds','p2')
			->where('p1.promoProd = p2')
			->andWhere( ':now BETWEEN p2.datedeb AND p2.datefin')
			->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
			->orderBy('p2.datedeb', 'ASC')
			->setMaxResults(1);
		$qb->andWhere($qb->expr()->in('prm', $subqb->getDQL()));*/

		return $qb->getQuery()->getResult();	
	}

	public function findSelec($categorie, $tri)
	{
		// 'u' est un alias qui va représenter un produit (puisqu'on le sélectionne dans l'entité Produit)
		// :categorie va représenter la catégorie passée en paramètre c'est à dire $categorie
		$qb = $this->createQueryBuilder('p')
			->where('p.disponible = 1')
			->orderBy('p.id');
		if($categorie != null){
			$qb = $qb->andWhere('p.categorie = :categorie')
					->setParameter('categorie', $categorie);
		}									
		if($tri == 'nom_asc') 	$qb = $qb->orderBy('p.nom', 'ASC');
		if($tri == 'nom_desc')	$qb = $qb->orderBy('p.nom', 'DESC');
		if($tri == 'pop_asc')	$qb = $qb->orderBy('p.popularite', 'ASC');
		if($tri == 'pop_desc')	$qb = $qb->orderBy('p.popularite', 'DESC');
		if($tri == 'prix_asc')	$qb = $qb->orderBy('p.prix', 'ASC');
		if($tri == 'prix_desc')	$qb = $qb->orderBy('p.prix', 'DESC');
		return $qb->getQuery()->getResult();
	}

	public function recherche($chaine)
	{
		//$lchaine = strtolower($chaine);
		$qb = $this->createQueryBuilder('u')
			->where('LOWER(u.nom) like :chaine')
			->andWhere('u.disponible = 1') 
			->orderBy('u.id')
			->setParameter('chaine', '%'.strtolower($chaine).'%' );
		return $qb->getQuery()->getResult();
	}

	public function preferred_tva($tva)
	{
		$qb = $this->createQueryBuilder('t')
			->select('t')
			->where('t.nom = :tva')
			->setParameter('tva', $tva);
		return $qb->getQuery()->getResult();		
	}

	public function findProdPromoProdById($id)
	{   
		/* Querybuilder recherche produit et leur promo en cours */
		/* Départ ProduitsRepository */
		$qb = $this->createQueryBuilder('prd');
		$qb ->where('p.id = :id')
			->join('prd.promoProd','prm')
			->addSelect('prm')
			->andWhere('prm.datefin >= :now')
			->andWhere('prm.datedeb <= :now')
			->orderBy('prm.datedeb', 'ASC')
			->setMaxResults(1)
			->setParameter(':id',$id)
			->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME) 
			;
		return $qb->getQuery()->getResult();
	}

	public function findAllProdPromoProdSelec($categorie, $tri)
	{   
		/* Querybuilder recherche produits et leur promo en cours */
		/* Départ ProduitsRepository */
		$subqb = $this->createQueryBuilder('p')	
			->where( ':now BETWEEN p.datedeb AND p.datefin')
			->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
			->orderBy('p.datedeb', 'ASC')
			->setMaxResults(1);

		$qb = $this->createQueryBuilder('prd')
			->leftjoin('prd.promoProd','prm')
			->addSelect('prm');

		$qb = $qb
			->andWhere($qb->expr()->in('prd.promoProd', $subqb->getDQL()));
		
		$qb = $qb
			->where('prd.disponible = 1')
			->orderBy('prd.id');
		if($categorie != null){
			$qb = $qb->andWhere('prd.categorie = :categorie')
					->setParameter('categorie', $categorie);
		}
									
		if($tri == 'nom_asc') 	$qb = $qb->orderBy('prd.nom', 'ASC');
		if($tri == 'nom_desc')	$qb = $qb->orderBy('prd.nom', 'DESC');
		if($tri == 'pop_asc')	$qb = $qb->orderBy('prd.popularite', 'ASC');
		if($tri == 'pop_desc')	$qb = $qb->orderBy('prd.popularite', 'DESC');
		if($tri == 'prix_asc')	$qb = $qb->orderBy('prd.prix', 'ASC');
		if($tri == 'prix_desc')	$qb = $qb->orderBy('prd.prix', 'DESC');
		return $qb->getQuery()->getResult();
	}	
}
