<?php

namespace DV\EcomBundle\Repository;

/**
 * PromoCmdesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCmdesRepository extends \Doctrine\ORM\EntityRepository
{
}
