<?php

namespace DV\EcomBundle\Repository;

/**
 * VisitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllVisites(){
		$qb = $this->createQueryBuilder('v')
				->select('SUM(v.nbrevisites) as total')
				;
		return $qb->getQuery()->getSingleScalarResult();	
	}
}
