parameters:
#    ecom.example.class: DV\EcomBundle\Example

services:
    setNewFacture:
        class:  AD\AdBundle\Services\GetFacture
        arguments: ['@service_container']

    setNewBL:
        class:  AD\AdBundle\Services\GetBL
        arguments: ['@service_container']

    setNewCgv:
        class:  AD\AdBundle\Services\GetCgv
        arguments: ['@service_container']

    setNewReassort:
        class:  AD\AdBundle\Services\GetReassort
        arguments: ['@service_container']