<?php

namespace DV\EcomBundle\Entity;

/**
 * VendeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendeurRepository extends \Doctrine\ORM\EntityRepository
{
}
