<?php

namespace Proxies\__CG__\GR7dev\appliEComBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Adresse extends \GR7dev\appliEComBundle\Entity\Adresse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'nomAdresse', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'adresse1', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'adresse2', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'cp', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'ville', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'pays', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'tel');
        }

        return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'nomAdresse', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'adresse1', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'adresse2', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'cp', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'ville', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'pays', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Adresse' . "\0" . 'tel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Adresse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomAdresse($nomAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomAdresse', array($nomAdresse));

        return parent::setNomAdresse($nomAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomAdresse', array());

        return parent::getNomAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse1($adresse1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse1', array($adresse1));

        return parent::setAdresse1($adresse1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse1', array());

        return parent::getAdresse1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse2($adresse2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse2', array($adresse2));

        return parent::setAdresse2($adresse2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse2', array());

        return parent::getAdresse2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', array($cp));

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', array());

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', array($pays));

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', array());

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

}
