<?php

namespace Proxies\__CG__\GR7dev\appliEComBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Detail extends \GR7dev\appliEComBundle\Entity\Detail implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'refproduit', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'nomComplet', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'marque', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'descLong', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'urlImgGde', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'etat', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'conditionnt', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'savoirPlus', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'gencod');
        }

        return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'refproduit', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'nomComplet', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'marque', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'descLong', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'urlImgGde', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'etat', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'conditionnt', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'savoirPlus', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Detail' . "\0" . 'gencod');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Detail $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefproduit($refproduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefproduit', array($refproduit));

        return parent::setRefproduit($refproduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefproduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefproduit', array());

        return parent::getRefproduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomComplet($nomComplet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomComplet', array($nomComplet));

        return parent::setNomComplet($nomComplet);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomComplet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomComplet', array());

        return parent::getNomComplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque($marque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', array($marque));

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', array());

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescLong($descLong)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescLong', array($descLong));

        return parent::setDescLong($descLong);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescLong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescLong', array());

        return parent::getDescLong();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlImgGde($urlImgGde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlImgGde', array($urlImgGde));

        return parent::setUrlImgGde($urlImgGde);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlImgGde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlImgGde', array());

        return parent::getUrlImgGde();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditionnt($conditionnt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditionnt', array($conditionnt));

        return parent::setConditionnt($conditionnt);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditionnt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditionnt', array());

        return parent::getConditionnt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSavoirPlus($savoirPlus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSavoirPlus', array($savoirPlus));

        return parent::setSavoirPlus($savoirPlus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSavoirPlus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSavoirPlus', array());

        return parent::getSavoirPlus();
    }

    /**
     * {@inheritDoc}
     */
    public function setGencod($gencod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGencod', array($gencod));

        return parent::setGencod($gencod);
    }

    /**
     * {@inheritDoc}
     */
    public function getGencod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGencod', array());

        return parent::getGencod();
    }

}
