<?php

namespace Proxies\__CG__\GR7dev\appliEComBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PromoCmde extends \GR7dev\appliEComBundle\Entity\PromoCmde implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'codePromoCmd', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'nom', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'remiseEuro', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'rabaisPourc', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'fraisPortGratuit', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'montantSeuil', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'datedeb', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'datefin');
        }

        return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'codePromoCmd', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'nom', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'remiseEuro', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'rabaisPourc', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'fraisPortGratuit', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'montantSeuil', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'datedeb', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\PromoCmde' . "\0" . 'datefin');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PromoCmde $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePromoCmd($codePromoCmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePromoCmd', array($codePromoCmd));

        return parent::setCodePromoCmd($codePromoCmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePromoCmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePromoCmd', array());

        return parent::getCodePromoCmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemiseEuro($remiseEuro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemiseEuro', array($remiseEuro));

        return parent::setRemiseEuro($remiseEuro);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemiseEuro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemiseEuro', array());

        return parent::getRemiseEuro();
    }

    /**
     * {@inheritDoc}
     */
    public function setRabaisPourc($rabaisPourc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRabaisPourc', array($rabaisPourc));

        return parent::setRabaisPourc($rabaisPourc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRabaisPourc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRabaisPourc', array());

        return parent::getRabaisPourc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisPortGratuit($fraisPortGratuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisPortGratuit', array($fraisPortGratuit));

        return parent::setFraisPortGratuit($fraisPortGratuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisPortGratuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisPortGratuit', array());

        return parent::getFraisPortGratuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantSeuil($montantSeuil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantSeuil', array($montantSeuil));

        return parent::setMontantSeuil($montantSeuil);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantSeuil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantSeuil', array());

        return parent::getMontantSeuil();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedeb($datedeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedeb', array($datedeb));

        return parent::setDatedeb($datedeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedeb', array());

        return parent::getDatedeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefin($datefin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefin', array($datefin));

        return parent::setDatefin($datefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefin', array());

        return parent::getDatefin();
    }

}
