<?php

namespace Proxies\__CG__\GR7dev\appliEComBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \GR7dev\appliEComBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'refProduit', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'nom', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'descCourt', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'urlImgMini', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'stockDispo', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'stockPhysique', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'poids', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'tva', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'detail', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'qualif', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'taille', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'promoProduit');
        }

        return array('__isInitialized__', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'refProduit', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'nom', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'descCourt', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'urlImgMini', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'stockDispo', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'stockPhysique', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'poids', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'tva', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'detail', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'qualif', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'taille', '' . "\0" . 'GR7dev\\appliEComBundle\\Entity\\Produit' . "\0" . 'promoProduit');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefProduit($refProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefProduit', array($refProduit));

        return parent::setRefProduit($refProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefProduit', array());

        return parent::getRefProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescCourt($descCourt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescCourt', array($descCourt));

        return parent::setDescCourt($descCourt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescCourt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescCourt', array());

        return parent::getDescCourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlImgMini($urlImgMini)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlImgMini', array($urlImgMini));

        return parent::setUrlImgMini($urlImgMini);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlImgMini()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlImgMini', array());

        return parent::getUrlImgMini();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockDispo($stockDispo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockDispo', array($stockDispo));

        return parent::setStockDispo($stockDispo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockDispo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockDispo', array());

        return parent::getStockDispo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockPhysique($stockPhysique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockPhysique', array($stockPhysique));

        return parent::setStockPhysique($stockPhysique);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockPhysique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockPhysique', array());

        return parent::getStockPhysique();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoids($poids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoids', array($poids));

        return parent::setPoids($poids);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoids', array());

        return parent::getPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\GR7dev\appliEComBundle\Entity\Categorie $categorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetail(\GR7dev\appliEComBundle\Entity\Detail $detail = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetail', array($detail));

        return parent::setDetail($detail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetail', array());

        return parent::getDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualif(\GR7dev\appliEComBundle\Entity\Qualif $qualif = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualif', array($qualif));

        return parent::setQualif($qualif);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualif', array());

        return parent::getQualif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille(\GR7dev\appliEComBundle\Entity\Taille $taille = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', array($taille));

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', array());

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoProduit(\GR7dev\appliEComBundle\Entity\PromoProduit $promoProduit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoProduit', array($promoProduit));

        return parent::setPromoProduit($promoProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoProduit', array());

        return parent::getPromoProduit();
    }

}
