validationCommande:
    path:     /api/banque/{id}
    defaults: { _controller: EcomBundle:Commandes:validationCommande }

paiementfait:
    path:     /Commandes/paiementfait
    defaults: { _controller: EcomBundle:Commandes:paiementfait }  