produits:
    path:     /produits
    defaults: { _controller: EcomBundle:Produits:produits }

produits_tripar_nomAsc:
    path:     /tri/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }
    
produits_tripar_nom_desc:
    path:     /tri/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }

produits_tripar_pop_asc:
    path:     /tri/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }

produits_tripar_pop_desc:
    path:     /tri/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }

produits_tripar_prix_asc:
    path:     /tri/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }

produits_tripar_prix_desc:
    path:     /tri/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcomBundle:Produits:presentation }

presentationpage:
    path:     /produit/{id}/{page}
    defaults: { _controller: EcomBundle:Produits:presentation }

categorieProduitstri:
    path:     /categorie/{categorie}/{tri}
    defaults: { _controller: EcomBundle:Produits:produits }

categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: EcomBundle:Produits:produits }

rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcomBundle:Produits:rechercheTraitement }

indexAvisProduits:
    path:     /avis/{id}
    defaults: { _controller: EcomBundle:Produits:indexAvis }

listeAvisProduits:
    path:     /avis/liste/{id}
    defaults: { _controller: EcomBundle:Produits:listeAvis }

addAvisProduits:
    path:     /avis/ajouter/{id}
    defaults: { _controller: EcomBundle:Produits:addAvis }

validerAvisProduits:
    path:     /avis/valider
    defaults: { _controller: EcomBundle:ProduitsAdmin:validerAvis }

supprimerAvisProduits:
    path:     /avis/supprimer
    defaults: { _controller: EcomBundle:ProduitsAdmin:supprimerAvis }