adminAvis:
    path:     /
    defaults: { _controller: "EcomBundle:AvisAdmin:index" }

adminAvis_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcomBundle:AvisAdmin:edit" }

adminAvis_update:
    path:     /{id}/update
    defaults: { _controller: "EcomBundle:AvisAdmin:update" }
    methods:  [POST, PUT]

adminAvis_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcomBundle:AvisAdmin:delete" }
    methods:  [POST, DELETE]

adminAvis_modif:
    path:     /{id}/modif
    defaults: { _controller: "EcomBundle:AvisAdmin:modif" }
    methods:  [POST, PUT]  

adminAvis_valid:
    path:     /validés
    defaults: { _controller: "EcomBundle:AvisAdmin:avisvalid" }
