adminCategories:
    path:     /
    defaults: { _controller: "EcomBundle:CategoriesAdmin:index" }

adminCategories_show:
    path:     /{id}/show
    defaults: { _controller: "EcomBundle:CategoriesAdmin:show" }

adminCategories_new:
    path:     /new
    defaults: { _controller: "EcomBundle:CategoriesAdmin:new" }

adminCategories_create:
    path:     /create
    defaults: { _controller: "EcomBundle:CategoriesAdmin:create" }
    methods:  POST

adminCategories_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcomBundle:CategoriesAdmin:edit" }

adminCategories_update:
    path:     /{id}/update
    defaults: { _controller: "EcomBundle:CategoriesAdmin:update" }
    methods:  [POST, PUT]

adminCategories_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcomBundle:CategoriesAdmin:delete" }
    methods:  [POST, DELETE]
