
validation:
    path:     /validation
    defaults: { _controller: EcomBundle:Commandes:validation }

validationCommande:
    path:     /api/banque
    defaults: { _controller: EcomBundle:Commandes:validationCommande }

paiement:
    path:     /Commandes/paiement
    defaults: { _controller: EcomBundle:Commandes:paiement } 

apiBanque:
    path:     /api/Banque
    defaults: { _controller: EcomBundle:Commandes:apiBanque } 

apiPaypal:
    path:     /api/Paypal
    defaults: { _controller: EcomBundle:Commandes:apiPaypal } 

paiementfait:
    path:     /Commandes/paiementfait
    defaults: { _controller: EcomBundle:Commandes:paiementfait }  