panier:
    path:     /
    defaults: { _controller: EcomBundle:Panier:panier }

ajoutpanier1:
    path:     /ajouter/{id}
    defaults: { _controller: EcomBundle:Panier:ajouter }

ajoutpanier2:
    path:     /ajouter/{id}
    defaults: { _controller: EcomBundle:Panier:ajouter }

supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: EcomBundle:Panier:supprimer }
    
adresses:
    path:     /adresses
    defaults: { _controller: EcomBundle:Panier:adresses }

frlivraison:
    path:     /livraison
    defaults: { _controller: EcomBundle:Panier:frlivraison }

validation:
    path:     /validation
    defaults: { _controller: EcomBundle:Panier:validation }

livraisonAdresseSuppr:
    path:     /livraison/adresse/suppression/{id}
    defaults: { _controller: EcomBundle:Panier:adresseSuppression }

