produits:
    path:     /
    defaults: { _controller: EcomBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcomBundle:Produits:presentation }

categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: EcomBundle:Produits:produits }

rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcomBundle:Produits:rechercheTraitement }