parameters:
#    utilisateurs.example.class: Utilisateurs\UtilisateursBundle\Example

services:
#    utilisateurs.example:
#        class: %utilisateurs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    fos_user.doctrine_registry:
        alias: doctrine
